In [2]:
print("awolad")

awolad


In [3]:
import tensorflow as tf

In [6]:
tesor_zero_d = tf.constant(4)
print(tesor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
tensor_one_d = tf.constant([1, 2, 3, 4])
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [10]:
tensor_two_d = tf.constant([
  [1, 2],
  [3, 4],
  [5, 6]
  ])
print(tensor_two_d)
#Shape: (3, 2) indicates that the tensor has 3 rows and 2 columns.

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [17]:
tensor_three_d = tf.constant([
  [
    [1, 2],
    [3, 4],
    [5, 6]
    ],
  [
    [7, 8],
    [9, 10],
    [11, 12]
],
  [
    [13, 14],
    [15, 16],
    [17, 18]
  ],
  [
    [19, 20],
    [21, 22],
    [23, 0]
  ]
  ])
casted_tensor = tf.cast(tensor_three_d, tf.bool)
print(tensor_three_d)
print(casted_tensor)

tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23  0]]], shape=(4, 3, 2), dtype=int32)
tf.Tensor(
[[[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True False]]], shape=(4, 3, 2), dtype=bool)


In [18]:
tensor_string = tf.constant("Hello, World!")
print(tensor_string)

tf.Tensor(b'Hello, World!', shape=(), dtype=string)


In [19]:
tensor_one_d_string = tf.constant(["Hello", "World", "!"])
print(tensor_one_d_string)

tf.Tensor([b'Hello' b'World' b'!'], shape=(3,), dtype=string)


In [20]:
import numpy as np

In [21]:
np_array = np.array([1, 2, 3, 4])
print(np_array)

[1 2 3 4]


In [22]:
convert_tensor = tf.convert_to_tensor(np_array)
print(convert_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [23]:
eye_tensor = tf.eye(3)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [25]:
eye_tensor = tf.eye(
  num_rows=3,
  num_columns=None,
  batch_shape=None,
  dtype=tf.float32,
  name=None
)
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [29]:
eye_tensor = tf.eye(
  num_rows=3,
  num_columns=None,
  batch_shape=[2,2],
  dtype=tf.float32,
  name=None
)
print(3*eye_tensor)

tf.Tensor(
[[[[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]

  [[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]]


 [[[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]

  [[3. 0. 0.]
   [0. 3. 0.]
   [0. 0. 3.]]]], shape=(2, 2, 3, 3), dtype=float32)
